### ISSUE TITLE
Add support for LaravelGenerator

### ISSUE THREAD

**Issue by brenodouglas** [rdehnhardt/skeleton#14]
Today i tested this package and much like. 

But I missed having something more like a crud generator. I tested today [LaravelGenerator] (http://labs.infyom.com/laravelgenerator/) with bootstrap template which is the standard used in this project and had great results. It's very fast to create an application using a scaffold like that.

this command take magic:
``` 
php artisan infyom:scaffold $MODEL_NAME
``` 

If it is of interest I can make a pull request so that it can be evaluated and better tested.

att, Breno douglas

**Comment by rdehnhardt** [comment]
You can install this package in your project.

**Comment by brenodouglas** [comment]
Ok, i can, but isn't default for others user.
